package com.example.accessingdatamysql.language;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/language") // This means URL's start with /demo (after Application path)

public class LanguageController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private LanguageRepository languageRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewLanguage(@RequestParam String intl_id) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Language l = new Language();
    l.setIntl_id(intl_id);
    languageRepository.save(l);
    return "Saved2";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Language> getAllLanguages() {
    // This returns a JSON or XML with the users
    return languageRepository.findAll();
  }
  
}